import type { SiteTheme } from "../types/siteTheme";

export const defaultSiteTheme: SiteTheme = {
  id: "night-reading-room",
  name: "Night Reading Room",
  mode: "personal research blog",
  principle: "A readable paper archive with a quiet threshold mythology in the margins.",
  ink: "#0e120d",
  paper: "#17160f",
  panel: "rgba(26, 25, 17, 0.88)",
  text: "#f2e6c7",
  muted: "#b9ad88",
  accent: "#b8793a",
  accentTwo: "#7d6b8f",
  door: "#9a4929",
  glow: "rgba(184, 121, 58, 0.24)",
  shadow: "rgba(0, 0, 0, 0.42)",
  grain: 0.18,
  tilt: -2,
  density: 1.2,
};

export const selectedThemePreviews: SiteTheme[] = [
  {
    id: "purple-rail",
    name: "Purple Rail",
    mode: "yin rail, red accent",
    principle: "A red-purple game-board palette, made quiet enough for long reading.",
    ink: "#0f0b12",
    paper: "#1a131d",
    panel: "rgba(28, 20, 31, 0.9)",
    text: "#efe4d1",
    muted: "#b7a4b9",
    accent: "#bb6950",
    accentTwo: "#8b6aa2",
    door: "#71394b",
    glow: "rgba(139, 106, 162, 0.26)",
    shadow: "rgba(0, 0, 0, 0.5)",
    grain: 0.18,
    tilt: -2,
    density: 1.3,
  },
  {
    id: "star-mirror",
    name: "Star Mirror",
    mode: "cold mirror, warm lamp",
    principle: "Deep blue-black and mirror silver, warmed by a small gold lamp color.",
    ink: "#070b10",
    paper: "#10161b",
    panel: "rgba(16, 22, 27, 0.91)",
    text: "#e9e4d7",
    muted: "#9fb0b8",
    accent: "#d0a24b",
    accentTwo: "#7da1b0",
    door: "#60483a",
    glow: "rgba(125, 161, 176, 0.22)",
    shadow: "rgba(0, 0, 0, 0.55)",
    grain: 0.16,
    tilt: -3,
    density: 1.18,
  },
  {
    id: "ink-and-myoga",
    name: "Ink And Myoga",
    mode: "black ink, ginger leaf",
    principle: "A dark ink surface with a muted botanical secondary color.",
    ink: "#080a08",
    paper: "#11150f",
    panel: "rgba(17, 22, 16, 0.92)",
    text: "#e9e2cd",
    muted: "#9fac8c",
    accent: "#c0843d",
    accentTwo: "#8ca35f",
    door: "#73432a",
    glow: "rgba(140, 163, 95, 0.2)",
    shadow: "rgba(0, 0, 0, 0.52)",
    grain: 0.18,
    tilt: -1,
    density: 1.2,
  },
  {
    id: "back-room-green",
    name: "Back Room Green",
    mode: "cedar green, hidden bronze",
    principle: "Green is dominant but blackened, avoiding the common blue-purple web palette.",
    ink: "#070b08",
    paper: "#101711",
    panel: "rgba(16, 23, 17, 0.92)",
    text: "#e5dfc9",
    muted: "#9fae91",
    accent: "#b68b45",
    accentTwo: "#63835f",
    door: "#5b4b2f",
    glow: "rgba(99, 131, 95, 0.23)",
    shadow: "rgba(0, 0, 0, 0.53)",
    grain: 0.17,
    tilt: -1,
    density: 1.2,
  },
  {
    id: "apricot-altar",
    name: "Apricot Altar",
    mode: "dark apricot, dim violet",
    principle: "Warmer and more literary, with violet as a shadow color instead of a brand color.",
    ink: "#0e0b0a",
    paper: "#18100e",
    panel: "rgba(27, 18, 15, 0.91)",
    text: "#f2dec1",
    muted: "#b99982",
    accent: "#d17d4a",
    accentTwo: "#80627f",
    door: "#87422f",
    glow: "rgba(209, 125, 74, 0.24)",
    shadow: "rgba(0, 0, 0, 0.5)",
    grain: 0.19,
    tilt: -2,
    density: 1.28,
  },
  {
    id: "winter-backdoor",
    name: "Winter Backdoor",
    mode: "snow-blue trace",
    principle: "The coldest seasonal direction, with door warmth kept as contrast.",
    ink: "#07090d",
    paper: "#0e1219",
    panel: "rgba(15, 20, 28, 0.92)",
    text: "#e8e5dc",
    muted: "#9eaabb",
    accent: "#bd8b48",
    accentTwo: "#83a3c0",
    door: "#65443b",
    glow: "rgba(131, 163, 192, 0.22)",
    shadow: "rgba(0, 0, 0, 0.56)",
    grain: 0.15,
    tilt: -3,
    density: 1.2,
  },
];

export function cssVars(theme: SiteTheme) {
  return [
    `--ink:${theme.ink}`,
    `--paper:${theme.paper}`,
    `--panel:${theme.panel}`,
    `--text:${theme.text}`,
    `--muted:${theme.muted}`,
    `--accent:${theme.accent}`,
    `--accent-two:${theme.accentTwo}`,
    `--door:${theme.door}`,
    `--glow:${theme.glow}`,
    `--site-shadow:${theme.shadow}`,
    `--grain-opacity:${theme.grain}`,
    `--site-tilt:${theme.tilt}deg`,
    `--door-density:${theme.density}`,
  ].join(";");
}
